---
- name: ensure longhorn check script is present
  become: no
  get_url:
    url: https://raw.githubusercontent.com/longhorn/longhorn/v{{ longhorn_version }}/scripts/environment_check.sh
    dest: "{{ kube_install_files_folder }}/environment_check.sh"
    mode: 0700
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: execute longhorn check script
  become: no
  shell: ./environment_check.sh
  args:
    chdir: "{{ kube_install_files_folder }}" 

- name: ensure longhorn repo
  command: helm repo add longhorn https://charts.longhorn.io

- name: update helm repos
  command: helm repo update

- name: ensure longhorn priority class values
  blockinfile:
    path: "{{ kube_install_files_folder }}/priorityclass_longhorn.yaml"
    block: |
      apiVersion: scheduling.k8s.io/v1
      kind: PriorityClass
      metadata:
        name: longhorn
      value: 1000000
      globalDefault: false
      description: "Makes sure longhorn starts before all other workloads"
    create: yes

- name: ensure longhorn priority class values
  blockinfile:
    path: "{{ kube_install_files_folder }}/values_longhorn.yaml"
    block: |
      defaultSettings:
        priorityClass: longhorn
      persistance:
        defaultClassReplicaCount: 1
      longhornManager:
        priorityClass: longhorn
      longhornDriver:
        priorityClass: longhorn
      longhornUI:
        priorityClass: longhorn
    create: yes

- name: ensure longhorn priority class
  command: kubectl apply -n {{ namespace_name }} -f {{ kube_install_files_folder }}/priorityclass_longhorn.yaml

- name: ensure longhorn in namespace {{ namespace_name }}
  command: helm upgrade --install longhorn longhorn/longhorn --version {{ longhorn_version }} -n {{ namespace_name }} -f {{ kube_install_files_folder }}/values_longhorn.yaml