---
- name: docker setup playbook
  hosts: "{{ ansible_play_hosts }}"
  tasks:
  
  - name: install packages for using a repository over https
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      state: present
      update_cache: yes
    become: yes
    
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    become: yes

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=arm64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
      state: present
    become: yes 

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes
    become: yes

  - name: copy deamon.json for enabling systemd as driver
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
    become: yes

  - name: Create docker.service.d if it does not exist
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
    become: yes

  - name: Restart docker, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes
      name: docker
    become: yes
  
  - name: Add {{ ansible_user }} to the docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    become: yes