#Playbook for setting up fresh ubuntu instances
#start with flags "-u ubuntu -k" and enter password
---
- name: unbuntu setup playbook
  hosts: "{{ ansible_play_hosts }}"
  gather_facts: no
  tasks:
    - name: importing settings
      include_tasks: ubuntu_vars.yml

    - name: set hostname to {{ inventory_hostname }}
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
      become: yes


    # #copy ssh-key to clients https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
    - name: Register SSH-keys for ubuntu
      ansible.posix.authorized_key:
        user: "ubuntu"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + ssh_key_path) }}"
        exclusive: True

    - name: Remove swapfile from /etc/fstab
      mount:
        name: ['swap', 'none']
        fstype: swap
        state: absent
 
    - name: Disable swap
      command: swapoff -a
      #when: ansible_swaptotal_mb > 0
    
    
    #enable cgroup
    - name: add cgroup to file
      lineinfile:
        dest: /boot/firmware/cmdline.txt
        state: present 
        regexp: '^(.*rootfstype.*)$'
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
        backrefs: yes
      become: yes
    
    - name: reboot to apply changes
      reboot:
      become: yes

