---
- name: ensure key for helm repo
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  become: yes

- name: ensure helm repo
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
  become: yes

- name: ensure helm
  apt:
    name: helm
    state: present
    update_cache: yes
  become: yes