---
- name: copy the join command to server location
  copy:
    src: ../configuration/join_command
    dest: /tmp/join_command.sh
    mode: 0777
  become: yes

- name: join the node to cluster
  shell: /tmp/join_command.sh
  become: yes