---
- name: add key for opensuse kubic repo
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_linux_version }}/Release.key
    state: present
  become: yes

- name: add opensuse kubic repo
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_linux_version }}/ /
    state: present
  become: yes

- name: add key for opensuse cri-o repo
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ crio_linux_version }}/Release.key
    state: present
  become: yes

- name: add opensuse kubic repo
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ crio_linux_version }}/ /
    state: present
  become: yes

- name: install cri-o
  command: apt install {{ item }} -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
  loop:
    - cri-o
    - cri-o-runc
  become: yes

- name: hold cri-o version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - cri-o
    - cri-o-runc
  become: yes

- name: start cri-o
  systemd:
    name: crio
    state: started
    enabled: yes
  become: yes