---
- name: add br_netfilter and overlay to loaded modules
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      br_netfilter
      overlay
    create: yes
  become: yes

- name: activate br_netfilter and overlay
  shell: |
    modprobe br_netfilter
    modprobe overlay
  become: yes

- name: add k8s.conf to sysctl
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    create: yes
  become: yes

- name: apply k8s.conf
  shell: sysctl --system
  become: yes

- name: remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  become: yes

- name: disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: yes