---
- name: download calico deployment
  copy: 
    src: ../configuration/templates/calico.yaml
    dest: "{{ kube_install_files_folder }}/calico.yaml"
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: install calico
  command: kubectl apply -f calico.yaml
  args:
    chdir: "{{ kube_install_files_folder }}" 