---
- name: download calico deployment
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: "{{ kube_install_files_folder }}/calico.yaml"

- name: install calico
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  args:
    chdir: "{{ kube_install_files_folder }}" 