---
- name: ensure k8s configuration
  hosts: '{{ host }}'
  
  roles:
    - role: '../roles/ensure_helm'
    - role: '../roles/ensure_calico'
    - role: '../roles/ensure_longhorn'
      vars:
        namespace_name: 'longhorn'
    - role: '../roles/ensure_ingress_nginx'
      vars:
        namespace_name: nginx-ingress
