---
- name: ensure k8s configuration
  hosts: '{{ host }}'
  vars_files:
    - '../vars/cluster_version.yml'
  
  roles:
    - role: '../roles/ensure_helm'
    - role: '../roles/ensure_calico'
    - role: '../roles/ensure_longhorn'
