---
- name: include prepare unbuntu
  import_playbook: prepare_ubuntu.yml

- name: include ensure k8s cluster
  import_playbook: ensure_k8s_cluster.yml

- name: include configure k8s cluster
  import_playbook: configure_k8s_cluster.yml
  when: node_role == "master"